#GENERAL
environment:
  sdk: '>=2.18.1 <3.0.0'

name: wordbook

version: 2022.10.28



#GLOBAL
dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.5.3

  flutter_localizations:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  google_fonts: ^3.0.1

  package_info_plus: ^3.0.1

  percent_indicator: ^4.2.2

  provider: ^6.0.4

  url_launcher: ^6.1.6


dev_dependencies:
  pedantic_mono: any



#LOCAL
flutter:
  assets:
    - asset/

  uses-material-design: true